apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: ticdc-gcs-example
spec:
  version: v8.3.0
  pd:
    baseImage: pingcap/pd
    replicas: 3
    requests:
      storage: "10Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    replicas: 3
    requests:
      storage: "100Gi"
    config: {}
  tidb:
    baseImage: pingcap/tidb
    replicas: 2
    service:
      type: ClusterIP
    config: {}
  ticdc:
    baseImage: pingcap/ticdc
    replicas: 3
    sink:
      type: gcs
      config:
        bucket: tidb-data-lake
        path: cdc-data
        accessKeySecretRef:
          name: ticdc-gcs-credentials
          key: access-key
        secretAccessKeySecretRef:
          name: ticdc-gcs-credentials
          key: secret-access-key
---
apiVersion: v1
kind: Secret
metadata:
  name: ticdc-gcs-credentials
type: Opaque
stringData:
  access-key: "YOUR_GCS_ACCESS_KEY"  # Replace with your actual access key
  secret-access-key: "YOUR_GCS_SECRET_KEY"  # Replace with your actual secret key
